### ISSUE TITLE
Can't find route (RouteNotFoundException) for valid points

### ISSUE THREAD

**Issue by maarno** [itinero/routing#124]
Hey,

I'm trying to calculate a route between the following points:
3.063034,101.4681 to 3.040579,101.4456
var routerPointFrom = Routers[this._map].TryResolve(Vehicle.Car.Fastest(), new Coordinate(3.063034f, 101.4681f), 300); // Value is {3971@12.5% [3.063034,101.4681] }

var routerPointTo = Routers[this._map].TryResolve(Vehicle.Car.Fastest(), new Coordinate(3.040579f, 101.4456f), 300); // Value is {26000@36.1% [3.040579,101.4456] }

var route = Routers[this._map].TryCalculate(Vehicle.Car.Fastest(), routerPointFrom.Value, routerPointTo.Value);

The calculation fails. route.IsError is true.

I'm using a contracted map of malaysia-singapore-brunei-latest.osm (http://download.geofabrik.de/asia/malaysia-singapore-brunei-latest.osm.pbf)

Itinero version is 1.3.0

Google Maps is able to find a route and http://www.yournavigation.org/ (based on OSM) too.

![image](https://user-images.githubusercontent.com/16541417/29698841-14bbc274-898b-11e7-849c-2b44712e05a9.png)

Any ideas what could be the problem?
Other locations work fine...

**Comment by xivk** [comment]
Sorry, no, I'll have to check this, could take a couple of days.

**Comment by maarno** [comment]
thank you. Have you had time to reproduce the problem?

**Comment by xivk** [comment]
This is fixed now, but fix is not yet default behaviour, the issue was a routing island:

http://geojson.io/#id=gist:anonymous/537575a2d0272a025d7e8fc9b3bfcd4c&map=18/3.06370/101.46811

If you look closely you will see there is no way to escape there. A new algorithm was implemented to detect islands and it's going to be default when contracting. This is the resulting route, it will just ignore the invalid part of the network:

http://geojson.io/#id=gist:anonymous/86bd917bceb5b2c2821929c84777bd9b&map=18/3.06201/101.46775
