### ISSUE TITLE
Different syntax of returned profile.FullName value of car.shortest() and car.fastest()

### ISSUE THREAD

**Issue by pingurus** [itinero/routing#161]
When calling car.shortest(), profile.FullName is "Car.Shortest" and profile.Name is "Shortest" . However, when calling car.fastest(), profile.FullName is "Car" and profile.Name is "". I guess this is a bug, or am I doing something wrong?

**Comment by xivk** [comment]
This is not a bug, this is by design. The names are setup `{vehicle}.{profile}` and fastests is the default and has no name. This means for car for example:

- `Car`: Fastest route. In this case the name is an empty string, fullname is _Car_
- `Car.Shortest`: Shortest route, in this case the profile name is _Shortest_ and the fullname is _Car.Shortest_.

**Comment by pingurus** [comment]
Thanks!
