### ISSUE TITLE
Status of Customizable Contraction Hierarchies

### ISSUE THREAD

**Issue by jerryfaust** [itinero/routing#208]
Hello.  I'm sorry to be opening a new Issue for an existing request (#92, also #119), but I'm not sure how else to request the status since the issues have been closed.

Can you tell me the development status of this feature?  I'm only asking for the sake of planning a related project.  If work has been done, I am willing to help test/debug.

Thank you.
Jerry.

**Comment by xivk** [comment]
The issues have been closed because this had been added to the roadmap. That being said there is still no eta. I added a section to the roadmap documentation explaining how our priorities are determined:

https://docs.itinero.tech/docs/itinero/development/index.html

These priorities also sometimes change depending on the needs of whoever is funding us, I hope you can understand that.

This is a great feature and one of my personal goals to get this implemented. We will also be getting an extra full-time team member soon but still I can't guarantee this is going to happen any time soon.

**Comment by xivk** [comment]
A small update, we will actually start working on this. It's on the development plan now. No ETA because this is not going to be trivial, expect 2019.

Closing this again, this is on the backlog. Stay tuned for Itinero 2.
