### ISSUE TITLE
Wrong way in roundabout

### ISSUE THREAD

**Issue by emij** [itinero/routing#31]
I have tried to modify Itinero to be able to route on HERE-data, but the routing is not correct. The route does not properly handle one-way-roads or roundabouts. It seems to have the wrong link id during routing (as in the attributes that checks for roundabouts and one-way is false because it checks the wrong roads, even though the coordinates is correct). So I tried to test it on the NWB-sample that are included in the project. It will get the correct link ids on the roads in the route, but it still seems to take the wrong route in the roundabouts. I have included a screenshot, the code I am running as well as a smaller sample of the NWB-shape file and the corresponding routerdb-file.
[nwb.zip](https://github.com/itinero/routing/files/615780/nwb.zip)

**Comment by xivk** [comment]
I'll have a look. Most likely cause is that the car.lua profile is not 100% correct, you need to make sure that roundabouts are also considered oneway by default. In the NWB profile this is here:

https://github.com/itinero/routing/blob/develop/samples/Sample.Shape/car.lua#L55

There is nothing to set the direction (0=bidirectional, 1=forward, 2=backward) for roundabouts. I'll try and figure out how to detect roundabouts in the NWB data and check if this fixes the issue. With HERE data this should be pretty straightforward.

**Comment by xivk** [comment]
Now I'm getting this route:

http://geojson.io/#id=gist:anonymous/72312e308644acd6e6497c729a3d5cdd&map=17/52.95471/6.33615

Looks better...

**Comment by emij** [comment]
This is my car.lua for HERE-data.
[car.lua.txt](https://github.com/itinero/routing/files/616129/car.lua.txt)
Every segment has a LINK_ID, and when checking which segments the routing are getting its attributes from to check for roundabouts it will look at the wrong segments, i.e. roads that are very far from the area where I do my routing.

**Comment by xivk** [comment]
Ok, I see, two things:

- You are including link_id in the profile. You should use the meta-data to store this.
- The shapefile reader should check for overflow when the number of profile types is too high.

Reason: Itinero limits the possible types of edges for performance reasons. There are max 16384 possible combinations, this way it can calculate for all profiles a speed/factor and then just use the precalculated values without re-reading the attributes during routing (is costly). 16384 should be more than enough when you include only attributes used for routing. 

In your case you use:  "ROUNDABOUT", "RAMP",  "DIVIDER",  "FUNC_CLASS",  "SPEED_CAT", "LINK_ID", "DIR_TRAVEL". Because of "LINK_ID" every edge has a unique profile overflowing the max of 16384. This means 16385 will become '0' etc... I'm implementing a check for this right now to prevent this from happening in the future. The OSM reader makes sure this doesn't happen, the shape reader doesn't.

You should update the lua profile:

```
-- whitelists for profile and meta
profile_whitelist = {
    "ROUNDABOUT", 
    "RAMP", 
    "DIVIDER", 
    "FUNC_CLASS", 
    "SPEED_CAT",
    "DIR_TRAVEL"
}
meta_whitelist = {
    "ST_NAME",
    "LINK_ID"
}
```

**Comment by emij** [comment]
I tried the routing on NWB now and it works, nice.
Ah, that would explain some things. I have made the changes now, and it seems to be working. Thanks!

**Comment by xivk** [comment]
No problem, thanks for testing and reporting, if you also see something in the OpenLR library, feel free to submit more issues.
