### ISSUE TITLE
loading several osm file into one RouterDb

### ISSUE THREAD

**Issue by ironromeo** [itinero/routing#47]
Unfortunately now "append" functionality is not allowed. I tried to remove blocking exception from RouterDbExtensions.cs and it looks like RouterDb was succesfully enlarged after loading one more .pbf file. Please make this functionality because I need to load several .osm.pbf into one RouterDb

**Comment by xivk** [comment]
The problem with this is that this will result in multiple separate graphs. Let's take the use case when you load two neighbouring countries, the ways at the border won't be joined, meaning you can't route from on country to the other.

The only way to do this is by merging the source osm.pbf files into one and then merging them together... I'll put some samples together so you can merge two osm.pbf files based on OsmSharp.

So, if I remove the check most users will expect the routerdb to be routable from one country to the other but that's impossible; it would mean storing the original node id's along with every routerdb and that would greatly increase memory used for no real gains because there is a workaround.

**Comment by alecava58** [comment]
Ok Ben. I'll wait the example on how to merge 2 or more pbf togheter.

thanks.

-- Alessandro

Il 30 dic 2016 11:34 PM, "Ben Abelshausen" <notifications@github.com> ha
scritto:

**Comment by xivk** [comment]
This is the code sample:

```
            // merge streams #1 and #2.
            var merge1 = new OsmSharp.Streams.Filters.OsmStreamFilterMerge();
            merge1.RegisterSource(new OsmSharp.Streams.PBFOsmStreamSource(
                File.OpenRead("path/to/file1.osm.pbf")));
            merge1.RegisterSource(new OsmSharp.Streams.PBFOsmStreamSource(
                File.OpenRead("path/to/file2.osm.pbf")));

            // optional: merge in #3
            var merge2 = new OsmSharp.Streams.Filters.OsmStreamFilterMerge();
            merge2.RegisterSource(merge1);
            merge2.RegisterSource(new OsmSharp.Streams.PBFOsmStreamSource(
                File.OpenRead("path/to/file3.osm.pbf")));

            // build routerdb from the merged stream.
            var routerDb = new RouterDb();
            routerDb.LoadOsmData(merge2, Itinero.Osm.Vehicles.Vehicle.Car);

            // write to disk.
            routerDb.Serialize(File.Open("output.routerdb", FileMode.Create));
```

A few remarks:

- One _OsmStreamFilterMerge_ can only merge two streams, you need to combine these to merge three or more.
- I discovered a bug with this in OsmSharp, **use at least v5.0.4-rc1 otherwise things will fail**.
- This is pretty new so no warranties but as long as you don't use OSM files from wildly different dates things should work fine. It's best to use extracts from the exact same day when merging them.

I will update Itinero so it requires at least this version of OsmSharp so this should keep working but that will have to wait, not a lot of time during the holidays.

**Comment by alecava58** [comment]
I'll try asap.

Many thanks and have a great 2017

-- Alessandro

Il 31 dic 2016 3:43 PM, "Ben Abelshausen" <notifications@github.com> ha
scritto:

**Comment by xivk** [comment]
- [ ] Add overload to load from multiple files at once.
- [ ] Update Itinero to depend on the latest OsmSharp including the merge fix.
