### ISSUE TITLE
TSP does not return to start

### ISSUE THREAD

**Issue by t22dk** [itinero/routing#50]
It looks like the newest nuget package has a small problem.

When i try to calculate TSP routes, it does not go back to the starting point.

And I can't find any options on the CalculateTSP function. It might be, that you could choose if it should return. This would be a nice feature. But the plain TSP should return to the start node, right ?.

BR
Martin.

**Comment by xivk** [comment]
Hi Martin,

The default on CalculateTSP is the 'Open TSP' version. If you add first and last equal to '0' then it should return back to the first customer.

Check here: https://github.com/itinero/optimization/blob/develop/src/Itinero.Optimization/RouterExtensions.cs#L49

There are three options:

- first=0, last=null: Open TSP, doesn't return to first.
- first=0, last=x: Closed TSP but with a fixed end customer 'x', also doesn't return to first.
- first=0, last=0: Closed TSP as you expect it to behave, returning back to the first. Perhaps this should be default yes.

Could you log future issues here?:

https://github.com/itinero/optimization

Please be aware that this code is still moving a lot, meaning things can change fast and are still relatively experimental. I'm expecting to have something more stable with basic documentation in 4 to 8 weeks.

Also, package name has changed to _Itinero.Optimization_. Closing this issue here, feel free to create new ones in the other repo about this.

**Comment by xivk** [comment]
Just to let you know I updated the readme with some more info:

https://github.com/itinero/optimization

Everything you need should be in there.
