### ISSUE TITLE
TryResolveConnect  problem

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#68]
Hi Ben,

I'm trying the TryResolveConnect but I'm facing a problem.

I'm using Luxembourg country and car vehicle with classifications profile.

If you try with the following set of coordinates TryResolveConnect failed (could not resolve ....) with the first one, but if you try to calculate the route is ok.

lat1 = 49.903820 lng1 = 6.119916
lat2 = 49.573916 lng2 = 5.937065

Note: if you use the fastest  profile everyrhing is ok.

**Comment by xivk** [comment]
Hmm ok, that could be due to the default parameters in TryResolveConnected and TryCheckConnectivity. The default there is distance. I would advise for now to use another profile to check connectivity and then use classifications to calculate the route. When the other profiles are connected, classifications profile is too, always.

For reference the problem is here:

https://github.com/itinero/routing/blob/d4b42bee831d9c17652dc5cc05952132e02116bc/src/Itinero/Router.cs#L151

This is a very subtle bug, thanks for catching this! 👍

**Comment by xivk** [comment]
There are few options to fix this:

1. Allow a custom radius, not just radiusInMeter, but this would be difficult to understand for users.
1. Allow only shortest profiles that use distance as a metric for a resolver.
1. Expand the profiles so it can be used with radiusInMeter.

Option 3 would change the profiles too much, option 2 is the easiest but violates the idea that you should always route and resolve using the same profile, so option1 is the best option for now.

This does not even require a change in this, we only need to rename the radius parameter.

Also related to #69

**Comment by alecava58** [comment]
option 2 is what I've done as workaround and it would be ok. Anyway option 1 is better.
Thanks,
